Mejora de Performance Descargador img telegramas
Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral pull request #116
Opened 2023-10-29 17:56 UTC by aridupuy

Mejora de Performance para descargar mucho mas rapido las imagenes de los telegramas del sistema de resultados oficial, utilizando varios hilos administrados por unix.

2023-10-29 17:56 UTC, aridupuy commented
@bonino97 creo que es asi jeje

2023-10-29 18:05 UTC, dody87 requested changes

2023-10-29 18:05 UTC, dody87 commented on Fuentes_de_datos/descargador_de_telegramas/command.php
> +            return 0;
podemos poner una variable al inicio resp = 1 y solo cambiar su valor y hacer el return, para evitar tantos puntos de returns asi sea mas facil el debug

2023-10-29 18:09 UTC, aridupuy commented on Fuentes_de_datos/descargador_de_telegramas/command.php
> +            return 0;
Perfecto! ya lo cambie!

2023-10-29 21:45 UTC, alelnro1 requested changes

2023-10-29 21:45 UTC, alelnro1 commented on Fuentes_de_datos/descargador_de_telegramas/DownloadImage.php
> +        curl_close($curl);
@aridupuy Podrias agregar una validacion por las dudas, algo asi:

```
        $response = curl_exec($curl);
        if (curl_errno($curl)) {
            error_log('Error de cURL en la mesa '.$mesa.': '.curl_error($curl));
            curl_close($curl);
            return false;
        }
        curl_close($curl);
```

2023-10-29 21:45 UTC, alelnro1 commented on Fuentes_de_datos/descargador_de_telegramas/command.php
> +    $mesa = $argv[2];
@aridupuy Podiras sanitizar los inputs para mayor seguridad, asi:

```
function sanitizeInput($input) {
    // Implementar una función de saneamiento según las necesidades
    return htmlspecialchars($input, ENT_QUOTES, 'UTF-8');
}

$directory = sanitizeInput($argv[1]);
$mesa = sanitizeInput($argv[2]);
```

2023-10-29 21:45 UTC, alelnro1 commented on Fuentes_de_datos/descargador_de_telegramas/command.php
> +        chmod($output_file,777);
@aridupuy Convendria que le pongas permisos de una formas mas asegura, asi:

`chmod($output_file, 0644);`

2023-10-29 21:45 UTC, alelnro1 commented on Fuentes_de_datos/descargador_de_telegramas/threadedCommand.php
> +            $file = $directory.$mesa.'.jpg';
@aridupuy  Sanitizar para evitar inyección de comandos
```
$mesa = escapeshellarg($mesa);
$file = $directory . $mesa . '.jpg'
```;

2023-10-29 21:45 UTC, alelnro1 commented on Fuentes_de_datos/descargador_de_telegramas/DownloadImage.php
> +        return $responseParsed->encodingBinary;
@aridupuy Esto se puede simplificar asi:

```
        if (empty($responseParsed->encodingBinary)) {
            error_log('Telegrama faltante para la mesa '.$mesa);
            file_put_contents(__DIR__."/error_mesa.txt", 'Telegrama faltante para la mesa '.$mesa.PHP_EOL, FILE_APPEND);
            return false;
        }

        return $responseParsed->encodingBinary;
```

1. Eliminación de touch: Eliminar el uso de touch y utilicé directamente file_put_contents con el flag FILE_APPEND. Este flag asegura que si el archivo ya existe, el nuevo contenido se añadirá al final del archivo existente, y si no existe, se creará el archivo
2. Mejor Manejo de Errores: Si el campo encodingBinary está vacío, registro un error en el log y escribo en el archivo de error, luego retorno false. Esto hace que la función sea más coherente en su comportamiento, indicando claramente que hubo un fallo en el procesamiento
3. Simplificación del Código: Consolidé la cadena de error en una sola línea, haciendo el código más limpio y fácil de mantener

2023-10-30 12:40 UTC, alelnro1 approved these changes

2023-10-30 14:32 UTC, jcarle approved these changes

2023-10-30 15:06 UTC, 06807 commented
出差外約+賴w8550  或賴06807   推薦臺灣小姐名單網站：www.ny076699.com   #臺灣高檔飯店#高檔酒店#高檔五星級飯店約小姐#找小姐賴06807    #出差臺灣旅遊 #吃魚 #定點旅館 賴06807 #汽車旅館#

喝茶+賴w8550   #高檔網紅 #高檔臺妹 #臺南外約 #高雄外約賴06807   #吃魚喝茶推薦 +賴w8550 #臺灣吃魚喝茶推薦 #臺灣定點茶 #固定茶 #外籍混血兒茶+賴w8550   #雙胞胎姐妹茶 #閨蜜茶 #酒店妹茶 #

母女茶 #新竹外約 #彰化外約賴06807 #南投外約 #臺中外約 #仁德外約賴06807  #桃園外約 #新北外約 #臺北外約 賴06807 做愛做的事加入telegram聊天賬號：https://t.me/m86633

臺灣吃魚喝茶推薦賴06807 或賴w8550   推薦TG賬號： https://t.me/m86633  #爆乳學生#大奶學生妹#無套內射熟女賴w8550#老熟女#技術口活好極品騷貨：免費看裸照：：http://www.ny076699.com
台灣約炮做愛+賴06807 或賴w8550  #爆乳學生#大奶學生妹#無套內射熟女賴w8550#老熟女#技術口活好極品騷貨：免費看裸照：：http://www.ny076699.com

台灣外送茶NO.1-line賴妹加電報telegram頻道：http://www.ny076699.com
line約妹-telegram約妹  您的私人外約顧問
全台均可外送，外送茶價格最良心
桃子外送茶論壇 老司機都在推薦的茶莊

老字號外約專家，經驗最強
顧客強力回流、評價一級棒！

新妹不斷天天入場，讓你百吃不厭！
外約茶專業團隊幫哥哥備好菜單~
一對一刺激你的神經，撫慰你的感官！

1：全台灣熟女.老女人口碑頻道：https://t.me/nw8433
2：新竹/竹北看照：https://t.me/w84333333
3：高雄/臺南看照：https://t.me/w8433333
4：臺中/彰化看照：https://t.me/w843333
5：臺北/新北看照：https://t.me/w84333

私我電報telegram： @nnw8433
私我電報telegram： @nnw8433

1：成年人性愛影片頻道 ：https://t.me/+UAHCykbVSdw2ZjRl
2：老司機開車聊色約砲玩一夜情頻道：https://t.me/+hwcR_1wNwssxMWZl
3：全臺服務地區：雙北-林口-龜山萬壽路-新竹-臺中-彰化-高雄-臺南
4：外約旅館-現金消費-【不轉賬-不匯款-不買點數】
5：全台灣：桃子外送茶約妹做愛炮：www.ny076699.com
6：營業時間：早上10：00--凌晨02：00【可提前預約】
熱門搜索：台灣約妹 /台灣叫小姐/+賴06807台灣定點/個人約砲/口碑茶/台灣旅旅遊出差找五星級酒店/飯店：桃子外送茶：www.ny076699.com
台灣外送叫小姐#台灣旅遊#台灣飯店叫小姐#台灣酒店玩一夜情賴W8550 #出差旅游臺灣玩女人
#賴W8550 台北約炮#新竹約炮#彰化約炮+賴06807台中約炮#高雄約炮#台南約炮賴W8550 #南投約炮#臺灣外送茶
台灣外送茶＃台北外送茶＃台中外送茶＃高雄外送茶＃新竹外送茶
＃彰化外送茶＃台南外送茶＃出差旅遊＃外約＃打炮攻略茶莊！
台北汽車旅館叫小姐.安排住家 新北摩鐵汽車旅館叫小姐 台南外送+洛洛舒壓按摩.桃園護膚全套外約.台北優質外送茶莊.新北出差旅遊約妹 中山區找小姐舒壓按摩.彰化員林汽車旅館叫妹妹服務.高雄

左營楠梓酒出差旅遊約妹 .新竹正妹 台中約情人.沙鹿豐原找女人兼職妹.推薦大台灣小檸檬茶莊外送茶看照約妹#林口龜山八里 外約妹妹價位#高雄雙北找小姐.彰化南投全套外送 高雄辣妹.楠梓找學生

妹人妻.鳳山台南哪裡美女最多+賴06807.台中彰化旅館 酒店外送小姐.雲林住家叫小姐上門服務/前鎮飯店叫小姐/ 北中南看照選妹影片選妹 Telegram賬號：nnw8433台灣美女外約學生妹“處女”校花三

線名模混血辣妹空姐援交妹模特麻豆 淫蕩熟女爆乳無套內射口爆肛交後門外約雙胞胎3p兼職下海姐妹3p閨蜜3p母女3p+超級巨乳|F奶|G奶|H奶|K奶. #+賴06807淫蕩巨乳無套妹#童顏巨乳#高端藝人.網

紅兼差 三線小模、三線藝人、學生、空姐、處女、單親媽媽、熟女人妻不等報班、 孕婦兼職、大奶胖妹、肥胖妹90kg、輕熟女姐姐、單親媽媽+賴06807、貧乳學生、A罩杯嫩妹、御姐兼職、國文老

師、約性感姐、約長榮空姐、約三性人、約重口味妹學生妹 大學生妹 #輔仁學生妹#淡江學生妹兼職外約... #東海學生妹#國立學生妹 靜宜學+賴06807生妹兼職外約 #僑光學生妹+賴06807 #淡江學生妹

兼職外約/清華學生妹

紅牌大奶妹賴06807 或賴w8550   加入電報telegram約砲 聊騷： @nnw8433 舌頭好長，吐舌頭的動作真的好澀，完美顏射，高潮臉#口交 #顏射 #高潮臉
#大胸 #奶子 #?炮 #洋妞 #舔射 #?值 #口交 #?震 #野?
#制服 #情趣 #舔射 #顏值 #插嘴 #顏值 #深喉
靈活的香舌，口技一流#雀斑 #甜妹 #少女
#少女 #可愛紅牌大奶妹賴06807 或賴w8550   加入電報telegram約砲 聊騷： @nnw8433 #舌頭 #少女 #福利姬 #口?
#顏射 #女僕 #吞精 #深喉 #完美口交賴w8550 
#口交 #妻子 #少婦 #按摩 #?所 #半套賴w8550 
#口交 #顏射 #高潮臉 #?射 #?射 #大屌#乳? #露出 #白虎
愛吃蛋，蛋蛋有營養 #舔蛋 #空姐 #偷情 #空降賴w8550 
 #完美口交 #偷情 #出差賴w8550  #人妻 #大三 #?生 #女友賴w8550 
手交，口交，肛交，小穴被排在了最後#手交 #口交 #肛交賴w8550 
#吞精 #口爆 #眼鏡娘 #甜妹賴w8550  #口交 #?值 JK少女被爸爸?教
#JK #少女 #?教 #?生賴w8550  #女高 #推特   #反差  #名媛
愛吃雞吧的小騷貨賴w8550  小?莉?口交 #反差婊 #少女 #包?賴w8550 
顏射 #擼射 #大屌 #小鹿? #三次元  #嫩逼 #足交 #00后 #??射精
#甜妹 #口交 #顏值 #YunaTamago #自慰 #女? #野? #?公室 #秘?賴w8550 
舌頭要放下去賴w8550 給女朋友看看吧。 #盯射 #口交#粉嫩 #极品 #?教
?熟女的?惑 #后入 #?妻 #露出 賴w8550 #粉嫩 #极品賴w8550  
#JK #黑襪 #女上賴w8550 
#?熟 #少女 #人妻賴w8550 
看好了，這才叫肉穴賴w8550 肉肉的，鼓鼓的，一插進去就能緊緊的包裹的你直吸氣。
全自動女友，扣6  加速賴w8550  無套內射大奶約砲賴84434 或賴06807   賴口爆內射肛交賴06807 
又騷又會撩  法式舌吻賴w8550 
逢甲學生妹 #東海學生妹 +賴06807#靜宜學生妹兼職外約旅遊台灣約炮做愛：約妹看照網址：http://www.ny076699.com
台大學生妹 #輔仁學生妹+賴06807 #淡江學生妹兼職外約旅遊台灣約炮做愛：約妹看照網址：http://www.ny076699.com
清華學生妹 #育達學生妹+賴06807 #交通大學生兼職外約旅遊台灣約炮做愛：約妹看照網址：http://www.ny076699.com
台南學生妹 #樹德學生妹 +賴06807#國立大學生兼職外約旅遊台灣約炮做愛：約妹看照網址：http://www.ny076699.com
樹德學生妹 #守義學生妹 +賴06807#輔英學生妹兼職外約旅遊台灣約炮做愛：約妹看照網址：http://www.ny076699.com
醫科學生妹 #守義學生妹 +賴06807#樹德學生妹兼職外約旅遊台灣約炮做愛：約妹看照網址：http://www.ny076699.com

2023-10-31 12:04 UTC, closed without merging