[FRONT] Selector actualizado al figma y filtros de resultados totales mock
Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral pull request #144
Opened 2023-10-29 23:08 UTC by Luddmilita

💄 Se actualizó el componente Selector para que sus estilos coincidan con los actuales

✅ Se creó la page `Filters` la cual son los filtros de los resultados totales

**Mobile:**
<img width="365" alt="Screen Shot 2023-10-29 at 20 07 21" src="https://github.com/Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral/assets/78838207/9d782dc7-d2e7-48f1-8ab9-7744eefe8f33">

**Desktop:**
<img width="1440" alt="Screen Shot 2023-10-29 at 20 07 35" src="https://github.com/Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral/assets/78838207/42e44f41-c576-48e8-8498-ff5a23d0e3b7">

2023-10-29 23:19 UTC, dody87 approved these changes

2023-10-30 01:11 UTC, ignasave requested changes

2023-10-30 01:11 UTC, ignasave commented on frontend/src/components/selector/Selector.tsx
> +                <SelectItem value={provincia} key={`${provincia} ${index}`} >{provincia}</SelectItem>
en vez de provincia siendo un componente general deberia ir algo tipo key values?

2023-10-30 01:11 UTC, ignasave commented on frontend/src/components/selector/Selector.tsx
> +                <SelectItem value={provincia} key={`${provincia} ${index}`} >{provincia}</SelectItem>
Estaria bueno que tambien sean controlados por el padre, o ya que usamos formik, dejar el handle para usarlo como input. hay que decidir aca.

2023-10-30 02:09 UTC, Luddmilita commented on frontend/src/components/selector/Selector.tsx
> +                <SelectItem value={provincia} key={`${provincia} ${index}`} >{provincia}</SelectItem>
Buenas como estas? si, opino lo mismo, pero como la card era mas que nada de mockear la screen de filtros no le di tanta bolilla ya que capaz conviene ver mas el tema lógica cuando tengamos backend ver que nos conviene dependiendo de como sean las responses/request. Que opinas?

2023-10-30 02:47 UTC, ignasave approved these changes

2023-10-30 02:54 UTC, bonino97 approved these changes

2023-10-30 02:54 UTC, merged