feat: validaciones en input de login
Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral pull request #154
Opened 2023-10-30 05:38 UTC by jeronimoek

se agrega formateo del input DNI
se implementan validaciones básicas en los input del login
se corrige el estilo de errores
se corrige eslint

2023-10-30 05:46 UTC, jeronimoek commented
![2023-10-30_02h44_57](https://github.com/Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral/assets/59717490/a64b89c5-9def-4ce9-b74b-76233f8aaef2)

2023-10-30 10:27 UTC, bonino97 requested changes

2023-10-30 10:27 UTC, bonino97 commented on frontend/.prettierrc
> +  "singleQuote": true
Rollback aca.

2023-10-30 10:27 UTC, bonino97 commented on frontend/.eslintrc.cjs
> +      {
Rollback aca.

2023-10-30 10:27 UTC, bonino97 commented on frontend/src/components/input/index.tsx
> +import classNames from 'classnames';
Fixea el orden de los imports.

2023-10-30 10:27 UTC, bonino97 commented on frontend/src/pages/login/login.tsx
> +import * as yup from 'yup';
Lo mismo, fix en el orden de los imports.

2023-10-30 10:27 UTC, bonino97 commented on frontend/src/pages/login/login.tsx
> +    dni: yup.string().required('Required field'),
El mensaje de error en español.

2023-10-31 11:55 UTC, bonino97 commented
@jeronimoek Hay conflictos en login.tsx, podras enviarme por discord? Asi mergeamos este PR? Abrazo!

2023-10-31 12:27 UTC, bonino97 commented
@jeronimoek lo mergie en el repo nuevo, mandame por DS cualq cosa, lo cierro por eso, esta actualizado ya.

2023-10-31 12:27 UTC, closed without merging