[FRONT] - Selector Fix
Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral pull request #172
Opened 2023-10-30 17:38 UTC by ignasave

Fixing selector component so we can control it from parent component.
Also we add types and fix the parent screen.

![ezgif com-video-to-gif](https://github.com/Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral/assets/43304840/6e6b9071-af00-4b7e-971c-87b63398646c)

2023-10-30 18:05 UTC, dody87 requested changes

2023-10-30 18:05 UTC, dody87 commented on frontend/src/pages/results/filter.tsx
> +const dummyData = [
falta tipado

2023-10-30 18:05 UTC, dody87 commented on frontend/src/pages/results/filter.tsx
> +  const [distrito, setDistrito] = useState('');
agregar tipo de datos en el generic <T>

2023-10-30 18:25 UTC, ignasave commented on frontend/src/pages/results/filter.tsx
> +const dummyData = [
El tipado viene de la interfaz del componente, para que la necesitas en la dummy data?

2023-10-30 18:26 UTC, ignasave commented on frontend/src/pages/results/filter.tsx
> +  const [distrito, setDistrito] = useState('');
Ok

2023-10-30 19:30 UTC, BrunoMPedraza requested changes
No todos los cambios son necesarios.

2023-10-30 19:30 UTC, BrunoMPedraza commented on frontend/src/pages/results/filter.tsx
> +  const [mesa, setMesa] = useState('');
Estas variables de estado deberían ser manejadas en un solo body, o incluso con un reducer.
Ejemplo de body
const [body, setBody] = useState<FilterForm>(FILTER_FORM_DEFAULT)

Después, sera llamado mediante setBody({...body, circuito: newCircuito})

En archivo constants.ts
FILTER_FORM_DEFAULT = { seccionElectoral: "", seccion .... (La verdad sería preferible esto en inglés).

interface IFilterForm { seccionElectoral: string, seccion:string  [...]

Esto reduce enormemente la cantidad de re-renderizados y centraliza la legibilidad.

2023-10-30 19:30 UTC, BrunoMPedraza commented on frontend/src/pages/results/filter.tsx
> +          <div className="px-3">
Usar gap en padre de main, no me parece obligatorio pero seguiría las reglas de caja de esta forma.

Esto sería agregando gap-2 y etiquetas contenedoras para section y h1, asi evitar tanto uso de propiedes como mt-10 que es mala idea. 
Es una observación, quizás no para este PR.

2023-10-30 19:30 UTC, BrunoMPedraza commented on frontend/src/pages/results/filter.tsx
> +              onChange={setMesa}
{keys.map((key) => (
        <Selector
          key={key}
          options={dummyData}
          placeholder={key}
          value={body[key]}
          onChange={(newValue) => handleChange(key, newValue)}
        />
      ))}

2023-10-30 19:30 UTC, BrunoMPedraza commented on frontend/src/pages/results/filter.tsx
> +            type="submit"
Hay 2 buttons de tipo submit.

2023-10-30 21:11 UTC, bonino97 commented on frontend/src/pages/results/filter.tsx
> +  const [mesa, setMesa] = useState('');
Si adhiero, si podes armar un solo state con todas las variables, y traducirlo a ingles perfecto. estamos manejando todo en un lenguaje solo menos texto hardcode. @ignasave

2023-10-30 21:11 UTC, bonino97 commented on frontend/src/pages/results/filter.tsx
> +            type="submit"
Adhiero. type='button'

2023-10-30 21:12 UTC, bonino97 commented on frontend/src/pages/results/filter.tsx
> +              onChange={setMesa}
Adhiero, crear un keys de selector con una logica similar a esta:  

![image](https://github.com/Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral/assets/24545141/4ab23637-5c1d-4075-976d-0717a213521b)
![image](https://github.com/Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral/assets/24545141/ba49cc00-0b54-4dc5-8cac-834d4d0dcca3)

2023-10-30 21:13 UTC, ignasave commented on frontend/src/pages/results/filter.tsx
> +              onChange={setMesa}
Esta bueno, el tema es que no se como viene la data todavia ,para tenerlo todo en la misma estructura pero aun no tenemos el back, mirá si despues de seleccionar cada data tenemos que fechear algo, tenemos que refactorizar de nuevo, solo cambie el select, eso es el PR

2023-10-30 21:16 UTC, ignasave commented on frontend/src/pages/results/filter.tsx
> +  const [mesa, setMesa] = useState('');
(Lo mismo de abajo). Esta bueno, el tema es que no se como viene la data todavia ,para tenerlo todo en la misma estructura pero aun no tenemos el back, mirá si despues de seleccionar cada data tenemos que fechear algo, tenemos que refactorizar de nuevo, solo cambie el select, eso es el PR

2023-10-30 21:17 UTC, ignasave commented on frontend/src/pages/results/filter.tsx
> +            type="submit"
No cambie eso en este PR es solo de los Select

2023-10-30 21:59 UTC, BrunoMPedraza commented on frontend/src/pages/results/filter.tsx
> +              onChange={setMesa}
Tenés razón que no habría que alejarnos demasiado pero esto justamente nos ayuda a re-centralizar cuando el mock de datos sea modificado, es más sencillo modificar un JSON que ir etiqueta por etiqueta.
Permitime subir un commit para ayudar al PR, dame unos minutos.

2023-10-30 22:43 UTC, BrunoMPedraza commented
Podríamos hacer unos cambios diminutos en lo que armaste, quedaría así. Lo subo como comentario debido a que es un fork y lo mio es solo una sugerencia, no quiero hacer un PR.

constants.ts
```
import { IFormBody } from './interfaces';

export const FORM_BODY: IFormBody = {
  distrito: '',
  seccionElectoral: '',
  seccion: '',
  municipio: '',
  establecimiento: '',
  mesa: '',
};

export const DUMMY_DATA = [
  { key: 'ex1', label: 'Example' },
  { key: 'ex2', label: 'Example 2' },
  { key: 'ex3', label: 'Example 3' },
];

```

interfaces.ts
```
export interface IFormBody {
  distrito: string;
  seccionElectoral: string;
  seccion: string;
  municipio: string;
  establecimiento: string;
  mesa: string;
}

```

```
import { Selector } from '#/components/selector';
import Button from '#/components/button';
import { observer } from 'mobx-react-lite';
import Navbar from '#/components/navbar';
import { useCallback, useState } from 'react';
import { DUMMY_DATA, FORM_BODY } from './constants';
import { IFormBody } from './interfaces';

const FilterPage = () => {
  const [body, setBody] = useState<IFormBody>(FORM_BODY)

  const handleChange = (key: keyof IFormBody, newValue: string) => {
    setBody(prevBody => ({
      ...prevBody,
      [key]: newValue,
    }));
  };

  const formatPlaceholder = useCallback((key: string) => {
    return key
      .replace(/([A-Z])/g, ' $1') 
      .replace(/_/g, ' ') 
      .replace(/^\w/, (c) => c.toUpperCase()); 
  },[]);
  return (
    <>
      <Navbar />
      <main className="items-center flex flex-col relative px-10">
        <section className="md:w-1/2 w-full rounded-xl z-10 mt-10">
          <h1 className="text-xl font-bold mb-6">Resultados totales</h1>
          <div className="px-3">
            {Object.keys(body).map((key) => (
              <Selector
                key={key}
                options={DUMMY_DATA}
                placeholder={formatPlaceholder(key)} 
                value={body[key as keyof IFormBody]}
                onChange={(newValue) => handleChange(key as keyof IFormBody, newValue)}
              />
            ))}
          </div>
          <Button
            className="mt-10 bg-violet-brand p-4 text-white w-full rounded-xl font-semibold text-xl tracking-wider"
            type="button"
            label="Aplicar Filtros"
          />
          <Button
            className="border-2 border-red text-red bg-transparent p-3 w-full rounded-xl text-xl tracking-wider shadow-md hover:border-violet-light mt-3"
            type="button"
            label="Alertar Irregularidades"
          />
        </section>
      </main>
    </>
  );
};

export const Filter = observer(FilterPage);

export default Filter;

```


De esta forma, el día de mañana cuando se cambien las muestras del backend será inmediato el cambio, y dejamos un código de muestra para otros formularios mapeables.

2023-10-30 22:50 UTC, BrunoMPedraza commented
No se si tenían la información, pero este repo esta deprecrado. Yo no la tenía o hubiera avisado antes.

2023-10-30 22:50 UTC, ignasave commented
@BrunoMPedraza No hay problema, esta bueno el cambio y no me opongo, no queria hacer mas largo este PR nomas. Si queres lo mergeamos y trabajamos arriba

2023-10-31 00:06 UTC, dody87 approved these changes

2023-10-31 00:06 UTC, dody87 commented on frontend/src/pages/results/filter.tsx
> +const dummyData = [
tenes razon

2023-10-31 01:10 UTC, BrunoMPedraza commented on frontend/src/pages/results/filter.tsx
> +          <div className="px-3">
No, me parece que no da para este PR

2023-10-31 12:03 UTC, bonino97 commented
@ignasave merged igna! lo cierro por q lo hcie a mano, mandame por discord cualq cosa.

2023-10-31 12:03 UTC, closed without merging