fix(readme): A lot of typos
Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral pull request #176
Opened 2023-10-30 19:16 UTC by AriDevK

Buenas tardes me intereso demasiado su proyecto y quise aportar, aunque sea un grano de arena intentando arreglar algunos errores ortográficos en el README. Personalmente considero que un proyecto así de serio y de esta índole no debería de contener este tipo de errores.

Saludos :3
![artworks-F11dor2dKfIo0DA6-zRbrxg-t500x500](https://github.com/Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral/assets/42656298/964e7bc0-29e8-4cad-834c-2e631350e896)

2023-10-30 19:20 UTC, BrunoMPedraza requested changes
Si bien estos 2 son errores ortográficos y nada más, se debería realizar un readme profesional.

2023-10-30 19:20 UTC, BrunoMPedraza commented on README.md
> +Esta es la lista de Tipos de Fraudes que se quieren atacar. Esa es la columna vertebral de este proyecto, de ahí deriva toda la funcionalidad que se va a construir. Si queres podes codear algo de lo
Codear no es una palabra real.

2023-10-30 19:20 UTC, BrunoMPedraza commented on README.md
>  ### Ficales Incompetentes
Fiscales va con S

2023-10-30 21:33 UTC, AriDevK commented on README.md
> +Esta es la lista de Tipos de Fraudes que se quieren atacar. Esa es la columna vertebral de este proyecto, de ahí deriva toda la funcionalidad que se va a construir. Si queres podes codear algo de lo
Entendido realizare el cambio; como duda los modismos como "tenes", "queres" ¿se deberán modificar por español neutro o se debería mantener?

2023-10-30 21:34 UTC, AriDevK commented on README.md
>  ### Ficales Incompetentes
Disculpa no entendí este punto; ya revise la palabra "Fiscales" en el documento y todas llevan "S" ¿podrías ser mas especifico?

2023-10-30 21:41 UTC, xplshn commented on README.md
> +Esta es la lista de Tipos de Fraudes que se quieren atacar. Esa es la columna vertebral de este proyecto, de ahí deriva toda la funcionalidad que se va a construir. Si queres podes codear algo de lo
Pasa que como programadores la mayoria de nosotros no tenemos el teclado en Espaniol(No tengo la N en el teclado, y no por vagancia de no querer cambiar el keymap, mi teclado no la tiene)

2023-10-30 21:54 UTC, BrunoMPedraza commented on README.md
>  ### Ficales Incompetentes
Línea 89, señalé mal yo en el comment

2023-10-31 01:13 UTC, BrunoMPedraza commented on README.md
> +Esta es la lista de Tipos de Fraudes que se quieren atacar. Esa es la columna vertebral de este proyecto, de ahí deriva toda la funcionalidad que se va a construir. Si queres podes codear algo de lo
No, igual me parece bien que quede. Igualmente hay un repositorio privado donde el readme es distinto.

2023-10-31 04:22 UTC, AlejandroZav approved these changes

2023-10-31 12:04 UTC, closed without merging