Frontend-Nextjs-tailwind
Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral pull request #19
Opened 2023-10-28 12:54 UTC by JoseOrtega02

2023-10-28 12:54 UTC, JoseOrtega02 commented
Adding Nextjs-tailwind frontend

2023-10-28 13:08 UTC, dody87 requested changes
Se podria instalar Typescript?

2023-10-28 13:17 UTC, JoseOrtega02 commented
ya estaria en teoria

2023-10-28 13:20 UTC, dody87 approved these changes

2023-10-28 14:01 UTC, RafaeLS85 approved these changes
es el boilerplate de next14 con tailwind y ts

2023-10-28 14:51 UTC, merged

2023-10-29 02:11 UTC, pflores86 commented
@JoseOrtega02 @Luis-Fernando-Molina  Deseo sumar mi aporte como FrontEnd dev