Add Dockerfile for fiscales-app-ts
Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral pull request #52
Opened 2023-10-28 15:35 UTC by navarroaxel

2023-10-28 15:44 UTC, brunocalmels commented
@navarroaxel podrías agregar algunas líneas al README sobre cómo configurar y utilizar el container? Así le facilitamos la vida a todos los que quieran contribuiur.

2023-10-28 17:06 UTC, navarroaxel commented
@brunocalmels listo.

2023-10-28 17:24 UTC, dody87 requested changes

2023-10-28 17:24 UTC, dody87 commented on Frontend/fiscales-app-ts/Dockerfile
> +RUN apk add --no-cache libc6-compat
para que es la llibc6-compat?

2023-10-28 17:27 UTC, navarroaxel commented on Frontend/fiscales-app-ts/Dockerfile
> +RUN apk add --no-cache libc6-compat
Alpine usa `musl libc` en lugar de `glibc`, por lo que ciertos software pueden tener problemas dependiendo de la profundidad de sus requisitos de `libc`.

2023-10-28 17:28 UTC, joaquinwojcik commented
Sumo evidencia de que levanta ok!
![image](https://github.com/Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral/assets/3205737/052a41fd-c908-4ff3-b18c-ed5d09d00ff9)

![image](https://github.com/Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral/assets/3205737/a68fc724-a4c2-4c37-bb41-dccf988b0bef)

2023-10-28 17:29 UTC, joaquinwojcik commented on Frontend/fiscales-app-ts/Dockerfile
> +RUN apk add --no-cache libc6-compat
@dody87 fyi

https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile#L6

2023-10-28 18:03 UTC, fastslack commented
Tienen que separar los repositorios muchachos para dockerizar bien

2023-10-28 20:21 UTC, luisgilg commented on Frontend/fiscales-app-ts/.env
No es una buena practica subir el archivo .env a un repositorio, se considera una vulnerabilidad, sugiero que se borre y en su lugar crear un archivo .env.example o similar con las variables de entorno con necesarias.

2023-10-28 20:22 UTC, luisgilg commented on Frontend/fiscales-app-ts/.env
Asi se evita que algún dev comparta información confidencial por error

2023-10-28 20:24 UTC, luisgilg commented on Frontend/fiscales-app-ts/.gitignore
> +*.idea/
Sugiero agregar acá el archivo .env para evitar que alguien suba información confidencial
```suggestion
*.idea/
.env
```

2023-10-28 21:07 UTC, navarroaxel commented on Frontend/fiscales-app-ts/.gitignore
> +*.idea/
en Next.js se usa el `.env.local` para poner secrets q no deber subirse. y ya esta incluido en el `.gitignore`.

2023-10-28 21:25 UTC, RosoPenaranda commented on Frontend/fiscales-app-ts/.env
en efecto, este archivo no deberia subirse:
- agrega el archivo al .gitignore
- ejecuta este comando: git rm --cached .env
- luego haz un commit para que se mantengan los nuevos cambios

2023-10-28 21:26 UTC, RosoPenaranda commented on Frontend/fiscales-app-ts/.gitignore
> +*.idea/
entiendo tu punto @navarroaxel de todos modos nada que no se utilice debe estar en el repositorio, en el comentario anterior comparti los pasos para eliminar el archivo

2023-10-28 21:29 UTC, RosoPenaranda commented on Frontend/fiscales-app-ts/Dockerfile
> +FROM node:20-alpine AS deps
seria bueno tener en cuenta donde se va a desplegar la app, no todos los servicios de cloud soportan las ultimas versiones de Node, pensaría que un lts del 18 seria buena opción, pero es solo una consideración que realizo

2023-10-28 21:31 UTC, RosoPenaranda commented on Frontend/fiscales-app-ts/docker-compose.yml
> +    image: node:20-alpine
la imagen no deberia ser el dockerfile que desarrollaste? Frontend/fiscales-app-ts/Dockerfile

2023-10-28 21:32 UTC, RosoPenaranda commented on Frontend/fiscales-app-ts/docker-compose.yml
> +    env_file: .env
en la respuesta de un comentario mas arriba dices que Nextjs utiliza .env.local, pero aca usas .env, al final cual de los 2 se va a usar, en esta linea puedes poner el nombre que tenga el archivo con tus variables no necesariamente debe llamarse .env

2023-10-28 21:41 UTC, navarroaxel commented on Frontend/fiscales-app-ts/docker-compose.yml
> +    env_file: .env
lo subi como un ejemplo. ni siquiera es necesario a esta altura

2023-10-28 21:48 UTC, RosoPenaranda commented on Frontend/fiscales-app-ts/docker-compose.yml
> +    env_file: .env
entiendo  de todos modos nada que no se utilice debe estar en el repositorio, en el primer comentario comparti los pasos para eliminar el archivo

2023-10-28 21:48 UTC, dody87 approved these changes

2023-10-28 21:49 UTC, dody87 commented
al menos uno mas que apruebe y mergeamos

2023-10-29 01:49 UTC, fernando143 requested changes
quitar .env del repo

2023-10-29 12:12 UTC, closed without merging

2023-10-29 12:12 UTC, Paw-liblab commented
Cierro ya que se migró el proyecto

2023-10-29 17:21 UTC, jd-apprentice commented
> Tienen que separar los repositorios muchachos para dockerizar bien, les recomiendo hacerlo ahora antes que se sume mas gente a ayudar. Si mantienen todo en un solo repo se les va a complicar despues

Es facil de mantener un monorepo con tan pocos proyectos

2023-11-01 12:48 UTC, arielromeo commented on Frontend/fiscales-app-ts/Dockerfile
> +ENV NODE_ENV production
Cuidado con esto que puede inducir a errores cuando se ejecute localmente y no en producción. Lo ideal sería que esta variable, la pase como un parámetro en tiempo de ejecución y que este se obtenga del ambiente.