Codebase inicial
Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral pull request #64
Opened 2023-10-28 21:32 UTC by snuffyxd

Pendiente...

2023-10-28 22:15 UTC, lmurature commented on scripts/telegramas-vs-api/src/run.js
> +        // menos de 95% de confianza no es un dato
95 o 50?

2023-10-28 22:19 UTC, lmurature commented on scripts/telegramas-vs-api/src/run.js
> +const ids = [
podemos levantar los ids mediante algun param al ejecutar o una config en un file en vez de tenerlo dentro del codigo?

2023-10-28 22:21 UTC, juanFernigrini commented
Tenes conocimiento pleno sobre la api? para extraer la base de distritos, secciones y demas para poder construir el request desde la db

2023-10-28 22:28 UTC, frangeris commented on scripts/telegramas-vs-api/src/run.js
> +const ids = [
Esto es el draft, podemos levantar desde donde querramos

2023-10-28 22:29 UTC, frangeris commented on scripts/telegramas-vs-api/src/run.js
> +        // menos de 95% de confianza no es un dato
Actualmente esta en `50` olvide actualizar el comment

2023-10-28 22:31 UTC, snuffyxd commented on scripts/telegramas-vs-api/src/run.js
> +        // menos de 95% de confianza no es un dato
Esta en 50 realmente

2023-10-28 22:32 UTC, snuffyxd commented
> Tenes conocimiento pleno sobre la api? para extraer la base de distritos, secciones y demas para poder construir el request desde la db

No, lamentablemente no, si se que viene todo por este request:

```bash 
GET https://resultados.gob.ar/backend-difu/nomenclator/getNomenclator
```

2023-10-28 22:33 UTC, snuffyxd commented on scripts/telegramas-vs-api/src/run.js
> +const ids = [
Podes levantar los IDs desde donde quieras, esto es solo un draft

2023-10-28 23:17 UTC, AlanKalbermatter commented on scripts/telegramas-vs-api/src/helpers.js
> +});
El espacio entre las constantes xD

2023-10-29 00:05 UTC, snuffyxd commented on scripts/telegramas-vs-api/src/helpers.js
> +});
Perdon, a que te referis?

2023-10-29 00:26 UTC, lsantobuono commented on scripts/telegramas-vs-api/src/run.js
> +const ids = [
Las mesas ya las vamos a tener en el sistema de una u otra forma imagino. ya que a ellas van a ser asociados los fiscales.

2023-10-29 01:43 UTC, fernando143 commented on scripts/telegramas-vs-api/src/run.js
> +        // menos de 95% de confianza no es un dato
@snuffyxd perdon, que seria esto? es la confianza del ocr cuando lee el texto?
Si es asi quizas aquellas que sean menos de 50 la podriamos encolar en algun lado para revision manual o algo asi se me ocurre

2023-10-29 14:00 UTC, snuffyxd commented on scripts/telegramas-vs-api/src/run.js
> +        // menos de 95% de confianza no es un dato
Correcto, 50% es la confianza que tiene el OCR sobre si el valor que detecto es el valor real, tuve que bajarlo porque pifiaba mucho, actualmente estoy saltandolas, si me brincan una cola mando el id de la mesa que no pude detectar

2023-10-29 14:21 UTC, frangeris commented on scripts/telegramas-vs-api/src/run.js
> +const ids = [
Chicos es lo de menos como pasarle el ID, ahora movere esto a una funcion para que las lambdas le peguen como helper

2023-10-29 14:33 UTC, dody87 requested changes

2023-10-29 14:33 UTC, dody87 commented on scripts/telegramas-vs-api/src/box.js
Se puede portear a type script ?

2023-10-29 15:20 UTC, snuffyxd commented on scripts/telegramas-vs-api/src/box.js
Si, eso es lo de menos, antes hay que hacerlo andar, pasare a draft y sigo agregando coords

2023-10-29 17:37 UTC, closed without merging

2023-11-16 22:33 UTC, nico2403 commented on scripts/telegramas-vs-api/src/run.js
> +const ids = [
Che tengo un sql con la datade los 7 niveles. Desde provincia hasta el código de mesa. Si alguien se copa podemos peinarlo todo con este dcrpt bello para encontrar irregilaridades